-- 001_initial_schema.sql
CREATE TABLE IF NOT EXISTS scraper_job_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Core fields
    source TEXT NOT NULL,
    external_id TEXT,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    url TEXT NOT NULL,
    
    -- Details
    location TEXT,
    location_city TEXT,
    location_state TEXT,
    location_country TEXT,
    
    salary_raw TEXT,
    salary_min NUMERIC,
    salary_max NUMERIC,
    salary_currency TEXT DEFAULT 'USD',
    
    description TEXT,
    job_type TEXT,
    remote BOOLEAN DEFAULT FALSE,
    experience_level TEXT,
    
    -- Metadata
    posted_at TIMESTAMPTZ,
    scraped_at TIMESTAMPTZ,
    
    dedup_hash TEXT UNIQUE NOT NULL,
    skills TEXT[],
    
    is_active BOOLEAN DEFAULT TRUE
);

-- Indexes
CREATE INDEX idx_scraper_job_listings_source ON scraper_job_listings(source);
CREATE INDEX idx_scraper_job_listings_dedup ON scraper_job_listings(dedup_hash);
CREATE INDEX idx_scraper_job_listings_posted_at ON scraper_job_listings(posted_at DESC);
