-- 008_dynamic_scraper_configs.sql

-- Table to store filter definitions for each spider
CREATE TABLE IF NOT EXISTS scraper_filter_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spider_id TEXT NOT NULL REFERENCES scraper_spider_configs(spider_id) ON DELETE CASCADE,
    filter_key TEXT NOT NULL, -- e.g., 'country', 'channels', 'daysReleased'
    display_name TEXT, -- e.g., 'Country', 'Job Channels'
    filter_type TEXT NOT NULL DEFAULT 'select', -- 'select', 'text', 'number', 'boolean'
    is_nested BOOLEAN DEFAULT FALSE, -- if true, this filter goes into the 'filters' object in payload
    default_value TEXT,
    is_required BOOLEAN DEFAULT FALSE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(spider_id, filter_key)
);

-- Table to store valid options for select-type filters
CREATE TABLE IF NOT EXISTS scraper_filter_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filter_definition_id BIGINT NOT NULL REFERENCES scraper_filter_definitions(id) ON DELETE CASCADE,
    option_label TEXT NOT NULL, -- e.g., 'USA', 'Germany'
    option_value TEXT NOT NULL, -- e.g., 'USA', 'DEU'
    group_name TEXT, -- e.g., 'IT & Technology' for subcategories
    metadata JSONB DEFAULT '{}', -- for any extra info
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(filter_definition_id, option_value)
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_scraper_filter_defs_spider_id ON scraper_filter_definitions(spider_id);
CREATE INDEX IF NOT EXISTS idx_scraper_filter_options_def_id ON scraper_filter_options(filter_definition_id);
