import os
from dotenv import load_dotenv
from supabase import create_client, Client

# Load environment variables
load_dotenv()

# --- SETUP ---
# Ensure these match what you have in job_leads_v1.py or your .env
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

def test_connection():
    print(f"Connecting to {SUPABASE_URL}...")
    try:
        client: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
        print("✅ Client created successfully.")
        return client
    except Exception as e:
        print(f"❌ Failed to create client: {e}")
        return None

def test_insert(client):
    table_name = "test_table"
    
    # Data to insert
    data = {
        "content": "Hello Supabase from Python!",
        "metadata": {"source": "test_script"}
    }

    print(f"Attempting to insert into '{table_name}'...")
    try:
        response = client.table(table_name).insert(data).execute()
        print(f"✅ Insert successful! Response: {response}")
    except Exception as e:
        print(f"❌ Insert failed: {e}")
        print("\nPossible fix: Does the table exist?")
        print("Run this SQL in your Supabase Dashboard -> SQL Editor:")
        print("-" * 40)
        print("""
        create table public.test_table (
          id bigint generated by default as identity primary key,
          created_at timestamp with time zone default timezone('utc'::text, now()) not null,
          content text,
          metadata jsonb
        );
        """)
        print("-" * 40)

if __name__ == "__main__":
    client = test_connection()
    if client:
        test_insert(client)
